import React from 'react';
import { AppIcon } from '../assets/appIcons';
import { registerApps } from '../core/appRuntime/appRegistry';

registerApps([
  {
    id: 'calculator',
    title: 'Calculator',
    icon: (props) => <AppIcon appId="calculator" {...props} />,
    component: () => import('./calculator/CalculatorApp'),
    defaultSize: { width: 300, height: 420 },
    minSize: { width: 260, height: 360 },
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'explorer',
    title: 'Explorer',
    icon: (props) => <AppIcon appId="explorer" {...props} />,
    component: () => import('./explorer/ExplorerApp'),
    defaultSize: { width: 620, height: 440 },
    minSize: { width: 380, height: 280 },
    singleInstance: true,
  },
  {
    id: 'terminal',
    title: 'Terminal',
    icon: (props) => <AppIcon appId="terminal" {...props} />,
    component: () => import('./terminal/TerminalApp'),
    defaultSize: { width: 560, height: 380 },
    minSize: { width: 340, height: 220 },
    singleInstance: true,
  },
  {
    id: 'settings',
    title: 'Settings',
    icon: (props) => <AppIcon appId="settings" {...props} />,
    component: () => import('./settings/SettingsApp'),
    defaultSize: { width: 460, height: 380 },
    minSize: { width: 400, height: 320 },
    singleInstance: true,
  },
  {
    id: 'readme',
    title: 'README',
    icon: (props) => <AppIcon appId="readme" {...props} />,
    component: () => import('./readme/ReadmeApp'),
    defaultSize: { width: 480, height: 460 },
    minSize: { width: 340, height: 300 },
    singleInstance: true,
  },
  {
    id: 'calendar',
    title: 'Calendar',
    icon: (props) => <AppIcon appId="calendar" {...props} />,
    component: () => import('./calendar/CalendarApp'),
    defaultSize: { width: 340, height: 520 },
    minSize: { width: 300, height: 440 },
    singleInstance: true,
  },
  {
    id: 'music',
    title: 'Music',
    icon: (props) => <AppIcon appId="music" {...props} />,
    component: () => import('./music/MusicApp'),
    defaultSize: { width: 320, height: 480 },
    minSize: { width: 280, height: 420 },
    resizable: false,
    singleInstance: true, // one AudioContext at a time keeps this simple and glitch-free
  },
  {
    id: 'messages',
    title: 'Messages',
    icon: (props) => <AppIcon appId="messages" {...props} />,
    component: () => import('./messages/MessagesApp'),
    defaultSize: { width: 460, height: 440 },
    minSize: { width: 380, height: 340 },
    singleInstance: true,
  },
  {
    id: 'community',
    title: 'Community',
    icon: (props) => <AppIcon appId="community" {...props} />,
    component: () => import('./community/CommunityApp'),
    defaultSize: { width: 420, height: 520 },
    minSize: { width: 320, height: 400 },
    singleInstance: true,
  },
  {
    id: 'internet',
    title: 'Internet',
    icon: (props) => <AppIcon appId="internet" {...props} />,
    component: () => import('./internet/InternetApp'),
    defaultSize: { width: 560, height: 420 },
    minSize: { width: 320, height: 260 },
    singleInstance: true,
  },
]);
