export const STORAGE_KEY = 'browseros:theme';
export const DEFAULT_THEME_ID = 'classic-pixel';

/**
 * BrowserOS theme packs combine palette, geometry, texture and a matching
 * wallpaper. They intentionally feel like different "machines", not simple
 * color swaps.
 */

function pixelCut(cut) {
  if (cut <= 0) return 'polygon(0 0, 100% 0, 100% 100%, 0 100%)';
  return `polygon(0 ${cut}px, ${cut}px ${cut}px, ${cut}px 0, calc(100% - ${cut}px) 0, calc(100% - ${cut}px) ${cut}px, 100% ${cut}px, 100% calc(100% - ${cut}px), calc(100% - ${cut}px) calc(100% - ${cut}px), calc(100% - ${cut}px) 100%, ${cut}px 100%, ${cut}px calc(100% - ${cut}px), 0 calc(100% - ${cut}px))`;
}

const common = {
  '--os-titlebar-height': '36px',
  '--os-dock-height': '64px',
  '--os-dock-gap': '10px',
  '--os-icon-size': '44px',
  '--os-icon-radius': '8px',
  '--os-ui-opacity': '0.94',
};

export const THEMES = {
  'classic-pixel': {
    label: 'Classic Pixel',
    description: 'Retro 90s computer',
    wallpaperId: 'classic-pixel',
    vars: {
      ...common,
      '--color-os-bg': '#2f73bd',
      '--color-os-bg-2': '#8cc9e8',
      '--color-os-surface': '#f0eee3',
      '--color-os-surface-2': '#d8d6c9',
      '--color-os-ink': '#171717',
      '--color-os-ink-soft': '#4f514f',
      '--color-os-accent': '#4d91d8',
      '--color-os-accent-ink': '#061a2e',
      '--color-os-mint': '#9ccf69',
      '--color-os-danger': '#c84c3f',
      '--color-os-border': '#8b8b82',
      '--color-os-border-strong': '#171717',
      '--os-radius-window': '3px',
      '--os-radius-sm': '2px',
      '--os-border-width': '2px',
      '--os-clip-corner': pixelCut(2),
      '--os-window-texture': 'repeating-linear-gradient(0deg, rgba(0,0,0,.035) 0 1px, transparent 1px 3px)',
      '--os-window-texture-size': 'auto',
      '--os-display-tracking': '0.03em',
      '--shadow-os-window': '4px 4px 0 rgba(0,0,0,.34), 0 12px 24px rgba(0,0,0,.22)',
      '--shadow-os-window-focused': '5px 5px 0 rgba(0,0,0,.45), 0 14px 28px rgba(0,0,0,.3)',
    },
  },
  'ukiyoe-calm': {
    label: 'Ukiyo-e Calm',
    description: 'Traditional Japanese art',
    wallpaperId: 'ukiyoe-calm',
    vars: {
      ...common,
      '--os-titlebar-height': '38px',
      '--os-dock-height': '62px',
      '--color-os-bg': '#b9ad8b',
      '--color-os-bg-2': '#ded1ac',
      '--color-os-surface': '#f3e8c9',
      '--color-os-surface-2': '#e4d5ae',
      '--color-os-ink': '#302b24',
      '--color-os-ink-soft': '#655846',
      '--color-os-accent': '#7b4d36',
      '--color-os-accent-ink': '#f7edd4',
      '--color-os-mint': '#71835b',
      '--color-os-danger': '#a44635',
      '--color-os-border': '#8f7d5a',
      '--color-os-border-strong': '#302b24',
      '--os-radius-window': '6px',
      '--os-radius-sm': '4px',
      '--os-border-width': '2px',
      '--os-clip-corner': pixelCut(3),
      '--os-window-texture': 'repeating-linear-gradient(0deg, rgba(76,58,39,.045) 0 1px, transparent 1px 4px)',
      '--os-window-texture-size': 'auto',
      '--os-display-tracking': '0.02em',
      '--shadow-os-window': '5px 5px 0 rgba(48,43,36,.18), 0 14px 28px rgba(48,43,36,.2)',
      '--shadow-os-window-focused': '5px 5px 0 rgba(123,77,54,.28), 0 16px 30px rgba(48,43,36,.25)',
    },
  },
  'sunset-drive': {
    label: 'Sunset Drive',
    description: 'Vaporwave sunset',
    wallpaperId: 'sunset-drive',
    vars: {
      ...common,
      '--color-os-bg': '#271b4b',
      '--color-os-bg-2': '#e15b8d',
      '--color-os-surface': '#2b173c',
      '--color-os-surface-2': '#3b1f50',
      '--color-os-ink': '#fff1f8',
      '--color-os-ink-soft': '#e7a7c8',
      '--color-os-accent': '#ff4eaa',
      '--color-os-accent-ink': '#21071d',
      '--color-os-mint': '#7ee9dc',
      '--color-os-danger': '#ff735f',
      '--color-os-border': '#8c4e98',
      '--color-os-border-strong': '#ff8cc8',
      '--os-radius-window': '4px',
      '--os-radius-sm': '3px',
      '--os-border-width': '2px',
      '--os-clip-corner': pixelCut(3),
      '--os-window-texture': 'repeating-linear-gradient(0deg, rgba(255,255,255,.045) 0 1px, transparent 1px 3px)',
      '--os-window-texture-size': 'auto',
      '--os-display-tracking': '0.08em',
      '--shadow-os-window': '0 0 0 1px rgba(255,78,170,.32), 0 8px 0 rgba(10,2,25,.5), 0 18px 36px rgba(0,0,0,.55)',
      '--shadow-os-window-focused': '0 0 0 2px rgba(126,233,220,.45), 0 8px 0 rgba(255,78,170,.45), 0 20px 40px rgba(0,0,0,.6)',
    },
  },
  'cyber-grid': {
    label: 'Cyber Grid',
    description: 'Dark neon terminal',
    wallpaperId: 'cyber-grid',
    vars: {
      ...common,
      '--color-os-bg': '#050a12',
      '--color-os-bg-2': '#071c2d',
      '--color-os-surface': '#07121e',
      '--color-os-surface-2': '#0a1b2a',
      '--color-os-ink': '#b8f8ff',
      '--color-os-ink-soft': '#62aebd',
      '--color-os-accent': '#00d9ff',
      '--color-os-accent-ink': '#001018',
      '--color-os-mint': '#55ffae',
      '--color-os-danger': '#ff527e',
      '--color-os-border': '#12617a',
      '--color-os-border-strong': '#00d9ff',
      '--os-radius-window': '2px',
      '--os-radius-sm': '1px',
      '--os-border-width': '1px',
      '--os-clip-corner': pixelCut(5),
      '--os-window-texture': 'repeating-linear-gradient(0deg, rgba(0,217,255,.055) 0 1px, transparent 1px 3px)',
      '--os-window-texture-size': 'auto',
      '--os-display-tracking': '0.11em',
      '--shadow-os-window': '0 0 0 1px rgba(0,217,255,.18), 0 0 24px rgba(0,217,255,.08), 8px 8px 0 rgba(0,0,0,.55)',
      '--shadow-os-window-focused': '0 0 0 1px rgba(0,217,255,.55), 0 0 28px rgba(0,217,255,.18), 8px 8px 0 rgba(0,0,0,.65)',
    },
  },
  'forest-retreat': {
    label: 'Forest Retreat',
    description: 'Peaceful woodland',
    wallpaperId: 'forest-retreat',
    vars: {
      ...common,
      '--color-os-bg': '#385449',
      '--color-os-bg-2': '#a9b59c',
      '--color-os-surface': '#e8e1cd',
      '--color-os-surface-2': '#d5d0bb',
      '--color-os-ink': '#243229',
      '--color-os-ink-soft': '#5d695f',
      '--color-os-accent': '#8a633f',
      '--color-os-accent-ink': '#fff6e4',
      '--color-os-mint': '#789b68',
      '--color-os-danger': '#b85b4b',
      '--color-os-border': '#8b927d',
      '--color-os-border-strong': '#243229',
      '--os-radius-window': '10px',
      '--os-radius-sm': '7px',
      '--os-border-width': '2px',
      '--os-clip-corner': pixelCut(2),
      '--os-window-texture': 'repeating-linear-gradient(90deg, rgba(36,50,41,.025) 0 1px, transparent 1px 5px)',
      '--os-window-texture-size': 'auto',
      '--os-display-tracking': '0.02em',
      '--shadow-os-window': '0 7px 0 rgba(36,50,41,.13), 0 16px 30px rgba(36,50,41,.2)',
      '--shadow-os-window-focused': '0 7px 0 rgba(138,99,63,.25), 0 18px 34px rgba(36,50,41,.24)',
    },
  },
  'space-explorer': {
    label: 'Space Explorer',
    description: 'Deep-space explorer',
    wallpaperId: 'space-explorer',
    vars: {
      ...common,
      '--color-os-bg': '#09091c',
      '--color-os-bg-2': '#27224f',
      '--color-os-surface': '#17132b',
      '--color-os-surface-2': '#211b3b',
      '--color-os-ink': '#f1eaff',
      '--color-os-ink-soft': '#aaa0c8',
      '--color-os-accent': '#c89bff',
      '--color-os-accent-ink': '#170c25',
      '--color-os-mint': '#78d8e8',
      '--color-os-danger': '#ff7894',
      '--color-os-border': '#554a7a',
      '--color-os-border-strong': '#d5b9ff',
      '--os-radius-window': '7px',
      '--os-radius-sm': '5px',
      '--os-border-width': '2px',
      '--os-clip-corner': pixelCut(4),
      '--os-window-texture': 'radial-gradient(circle, rgba(255,255,255,.11) 0 1px, transparent 1.5px)',
      '--os-window-texture-size': '17px 17px',
      '--os-display-tracking': '0.07em',
      '--shadow-os-window': '0 8px 0 rgba(0,0,0,.42), 0 0 25px rgba(200,155,255,.08), 0 18px 32px rgba(0,0,0,.42)',
      '--shadow-os-window-focused': '0 8px 0 rgba(0,0,0,.5), 0 0 32px rgba(200,155,255,.2), 0 20px 36px rgba(0,0,0,.55)',
    },
  },
};

export const THEME_IDS = Object.keys(THEMES);
export const THEME_VAR_KEYS = Object.keys(THEMES[DEFAULT_THEME_ID].vars);

export { pixelCut };
